-- MySQL Script generated by MySQL Workbench
-- Thu Oct 28 15:05:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`person` (
  `person_id` INT(8) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `age` INT(3) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `picture` VARCHAR(255) NULL,
  PRIMARY KEY (`person_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`address` (
  `address_id` INT(8) NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `house_number` VARCHAR(45) NULL,
  `zip_code` VARCHAR(45) NULL,
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`person_has_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`person_has_address` (
  `person_id` INT(8) NOT NULL,
  `address_id` INT(8) NOT NULL,
  `address_type` VARCHAR(45) NOT NULL,
  INDEX `user_íd_idx` (`person_id` ASC) VISIBLE,
  INDEX `address_id_idx` (`address_id` ASC) VISIBLE,
  PRIMARY KEY (`person_id`, `address_id`),
  CONSTRAINT `person_íd`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`person` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `address_id`
    FOREIGN KEY (`address_id`)
    REFERENCES `mydb`.`address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`role` (
  `role_id` INT(8) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`person_has_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`person_has_role` (
  `person_id` INT(8) NOT NULL,
  `role_id` INT(8) NOT NULL,
  INDEX `person_id_idx` (`person_id` ASC) VISIBLE,
  INDEX `role_id_idx` (`role_id` ASC) VISIBLE,
  PRIMARY KEY (`person_id`, `role_id`),
  CONSTRAINT `role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`person` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`film` (
  `film_id` INT(8) NOT NULL,
  `film_name` VARCHAR(45) NOT NULL,
  `PEGI` INT(3) NULL,
  PRIMARY KEY (`film_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`theatre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`theatre` (
  `theatre_id` INT(8) NOT NULL,
  `theatre_name` VARCHAR(45) NOT NULL,
  `address_id` INT(8) NOT NULL,
  PRIMARY KEY (`theatre_id`),
  INDEX `address_id_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `address_id`
    FOREIGN KEY (`address_id`)
    REFERENCES `mydb`.`address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`screen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`screen` (
  `screen_id` INT(8) NOT NULL,
  `screen_number` INT(2) NOT NULL,
  `is_3d` TINYINT NULL,
  `theatre_id` INT(8) NOT NULL,
  PRIMARY KEY (`screen_id`, `theatre_id`),
  INDEX `theatre_id_idx` (`theatre_id` ASC) VISIBLE,
  CONSTRAINT `theatre_id`
    FOREIGN KEY (`theatre_id`)
    REFERENCES `mydb`.`theatre` (`theatre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`film_has_screen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`film_has_screen` (
  `film_id` INT(8) NOT NULL,
  `screen_id` INT(8) NOT NULL,
  INDEX `screen_id_idx` (`screen_id` ASC) VISIBLE,
  INDEX `film_id_idx` (`film_id` ASC) VISIBLE,
  PRIMARY KEY (`screen_id`, `film_id`),
  CONSTRAINT `film_id`
    FOREIGN KEY (`film_id`)
    REFERENCES `mydb`.`film` (`film_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `screen_id`
    FOREIGN KEY (`screen_id`)
    REFERENCES `mydb`.`screen` (`screen_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`person_has_film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`person_has_film` (
  `person_id` INT(8) NOT NULL,
  `film_id` INT(8) NOT NULL,
  `is_customer` TINYINT NOT NULL,
  INDEX `film_id_idx` (`film_id` ASC) VISIBLE,
  INDEX `person_id_idx` (`person_id` ASC) VISIBLE,
  PRIMARY KEY (`film_id`, `person_id`),
  CONSTRAINT `film_id`
    FOREIGN KEY (`film_id`)
    REFERENCES `mydb`.`film` (`film_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`person` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contact` (
  `contact_id` INT(8) NOT NULL,
  `contact_type` VARCHAR(45) NOT NULL,
  `contact_value` VARCHAR(45) NOT NULL,
  `person_id` INT(8) NOT NULL,
  PRIMARY KEY (`contact_id`),
  INDEX `person_id_idx` (`person_id` ASC) VISIBLE,
  CONSTRAINT `person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`person` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`person_has_screen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`person_has_screen` (
  `person_id` INT(8) NOT NULL,
  `screen_id` INT(8) NOT NULL,
  `is_employee` TINYINT NOT NULL,
  INDEX `person_id_idx` (`person_id` ASC) VISIBLE,
  INDEX `screen_id_idx` (`screen_id` ASC) VISIBLE,
  PRIMARY KEY (`screen_id`, `person_id`),
  CONSTRAINT `person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`person` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `screen_id`
    FOREIGN KEY (`screen_id`)
    REFERENCES `mydb`.`screen` (`screen_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
